# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [ ]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.71623903 0.83421736 0.20283245 ... 0.12219372 0.85155766 0.08095535]
 [0.32400017 0.94725019 0.48172657 ... 0.59664808 0.05823933 0.69097417]
 [0.7915834  0.57377052 0.03549818 ... 0.6207668  0.688268   0.82270899]
 ...
 [0.4464072  0.06124678 0.90291684 ... 0.56878377 0.79122806 0.20716391]
 [0.13770132 0.26235205 0.01358659 ... 0.35316577 0.95593573 0.5806895 ]
 [0.82472043 0.67813063 0.10982063 ... 0.14306997 0.5796364  0.6773483 ]]
[[0.99977889 0.55456221 0.16467361 ... 0.87444132 0.72102559 0.73569217]
 [0.39429612 0.66489597 0.14928742 ... 0.8371945  0.75921631 0.29155441]
 [0.82322842 0.99415781 0.91063462 ... 0.81561557 0.73128897 0.24400266]
 ...
 [0.23378122 0.77557759 0.61370557 ... 0.86422687 0.30059227 0.83539716]
 [0.03488193 0.02202475 0.64674179 ... 0.46629705 0.46373327 0.92966594]
 [0.06925655 0.67849229 0.55412563 ... 0.36784648 0.32625138 0.59496034]]


Без использования numpy

In [ ]:
def mult(a, b):
    result = []
    # проверяем, что размерности матриц совпадают
    if len(a) == len(b) and len(a[0]) == len(b[0]):
        # проходим по строкам матрицы a
        for i in range(len(a)):
            row = []
            # проходим по столбцам матрицы b
            for j in range(len(b[0])):
                # вычисляем значение элемента в результативной матрице
                value = 0
                # проходим по элементам строки матрицы a и столбца матрицы b
                for k in range(len(a[i])):
                    value += a[i][k] * b[k][j]
                # добавляем значение в строку результата
                row.append(value)
            # добавляем строку в результативную матрицу
            result.append(row)
    else:
        print("Ошибка: размерности матриц не совпадают")
    return result

C использованием numpy

In [ ]:
def np_mult(a, b):
    result = None
    # проверяем, что размерности матриц совпадают
    if a.shape[0] == b.shape[1] and a.shape[1] == b.shape[0]:
        # умножаем матрицы с помощью функции dot
        result = np.dot(a, b)
    else:
        print("Ошибка: размерности матриц не совпадают")
    return result

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 644 ms, sys: 0 ns, total: 644 ms
Wall time: 648 ms


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 778 µs, sys: 57 µs, total: 835 µs
Wall time: 3.49 ms


In [ ]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.5219825399981346e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.42107511 0.72466918 0.95695925] [0.9149199  0.59761177 0.31914607]


In [ ]:
def scalar_product(a, b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s

In [ ]:
def np_scalar_product(a, b):
    return np.dot(a, b)

In [ ]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 34 µs, sys: 6 µs, total: 40 µs
Wall time: 57.7 µs
CPU times: user 36 µs, sys: 6 µs, total: 42 µs
Wall time: 46.7 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Методы NumPy оказываются эффективнее, потому что они используют векторизацию и оптимизированные алгоритмы для работы с массивами данных. В отличие от обычных циклов, которые выполняются последовательно, векторизация позволяет выполнять операции над массивами данных параллельно, что существенно ускоряет вычисления.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  res = 0
  for i in range(len(a)):
    if a[i][i] % 2 == 0:
      res += a[i][i]
    if a[i][-i-1] % 2 == 0:
      res += a[i][-i-1]
  return res

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[1, 8, 1, 4, 9],
       [9, 1, 9, 3, 8],
       [3, 5, 3, 2, 7],
       [5, 4, 3, 6, 1],
       [7, 1, 9, 5, 7]])

In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 32 µs, sys: 0 ns, total: 32 µs
Wall time: 35.8 µs


10

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(X):
    if len(X.shape) == 1:
        X = X.reshape(1, -1)
    result = np.cumsum(X, axis=1)
    return result

In [ ]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[7.51930847e-01 3.24508501e-01 1.73605042e-01 3.35160423e-01
 8.62164596e-01 8.14612454e-01 3.77601814e-01 8.14153375e-01
 7.88491920e-01 5.40389818e-01 2.08592546e-01 1.43168038e-01
 9.17063204e-01 5.60058671e-01 1.53652453e-01 5.98609091e-01
 4.45210129e-01 1.86444342e-01 3.28079714e-01 4.05052740e-01
 1.86548033e-01 4.35395900e-02 2.26970332e-01 1.48537475e-02
 3.98895494e-01 7.92344146e-01 7.74016509e-01 5.80517747e-01
 4.50111759e-01 8.71164219e-01 7.48056412e-01 1.47265593e-01
 4.58432027e-01 9.09002470e-01 9.96903836e-01 2.65389372e-01
 6.74307512e-01 6.61315989e-01 7.92330468e-02 9.42399839e-01
 2.19143642e-01 9.82053591e-01 3.36617298e-01 5.90984673e-01
 4.82933239e-01 7.26150471e-01 1.99692984e-01 8.37736657e-01
 2.68416185e-01 1.00453153e-01 4.60211909e-01 1.58332011e-01
 9.90699122e-01 8.84076687e-01 3.52584812e-01 3.44077725e-01
 3.62550735e-02 8.76217272e-01 1.09354890e-01 6.39237700e-02
 2.06607811e-01 6.68111506e-01 8.25074538e-01 1.59619983e-01
 5.31273981e-01 5.823097

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    if len(a) == 0:
        return (np.array([]), np.array([]))

    # Находим индексы, где происходит изменение значения
    change_indices = np.where(a[:-1] != a[1:])[0]

    # Добавляем последний элемент массива, чтобы учесть последний блок
    change_indices = np.concatenate((change_indices, [len(a) - 1]))

    # Считаем длину каждого блока
    lengths = np.diff(np.concatenate(([0], change_indices)))

    # Элементы после каждого изменения
    elements = a[change_indices]

    return elements, lengths

In [ ]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 140 µs, sys: 0 ns, total: 140 µs
Wall time: 145 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [ ]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    X_copy = np.copy(X)

    # Заменяем элементы с нечетными индексами на a
    X_copy[1::2] = a

    # Возводим элементы с четными индексами в куб
    X_copy[::2] **= 3

    # Создаем новый массив, который объединяет X и преобразованный X в обратном порядке
    result = np.concatenate([X, X_copy[::-1]])

    return result

In [ ]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 161 µs, sys: 27 µs, total: 188 µs
Wall time: 299 µs
